### ISSUE TITLE
Add heex support

### ISSUE THREAD

**Issue by mohammedzeglam-pg** [emacs-tree-sitter/tree-sitter-langs#106]
add heex binary to project or update how to build section in readme

**Comment by jsmestad** [comment]
@mohammedzeglam-pg I know it isn't in this repo yet, but you can add it yourself following [this blog post](https://blog.evalcode.com/elixir-heex-highlighting-in-emacs/)

**Comment by mohammedzeglam-pg** [comment]
> this blog post

thanks 🌷

**Comment by jcs090218** [comment]
Added in #268.
