### ISSUE TITLE
Add Latex support

### ISSUE THREAD

**Issue by sgpthomas** [emacs-tree-sitter/tree-sitter-langs#107]
It looks like there is already a grammar [here](https://github.com/latex-lsp/tree-sitter-latex).

**Comment by mkvoya** [comment]
BTW, there are also grammars for bibtex  https://github.com/latex-lsp/tree-sitter-bibtex and https://github.com/latex-lsp/tree-sitter-biber .

**Comment by jcs090218** [comment]
LaTex added in #230. BibTex is added in #205.

Please open another issue for biber! Thank you!
