### ISSUE TITLE
Add R language support for use in ess-r-mode

### ISSUE THREAD

**Issue by atanasj** [emacs-tree-sitter/tree-sitter-langs#109]
As per the heading. The repo for `tree-sitter` in `R` can be found here: https://github.com/r-lib/tree-sitter-r

**Comment by maikol-solis** [comment]
There is a package dedicated only for R tree-sitter language: 

https://melpa.org/#/tree-sitter-ess-r
https://github.com/ShuguangSun/tree-sitter-ess-r

I hope that `tree-sitter-ess-r` could be merge into the langs for maximum exposure. 

Best.

**Comment by meain** [comment]
R support should now be available from https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/132 and https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/133
