### ISSUE TITLE
Unsupported system-type `berkley-unix`

### ISSUE THREAD

**Issue by anoduck** [emacs-tree-sitter/tree-sitter-langs#141]
It appears I have tinkered my way through getting tree-sitter to run on OpenBSD, It was not fun. So, attempting to install grammar files, and then boom, that isn't supported either. From the looks of it, it appears that only Linux(libc based), macintosh, and of all things Windon't is supported. The rest of the open source community was left without support. 

If I can manage to hack my way into a working installation, it shouldn't be hard for someone much more knowledgeable to accomplish it, and it would be terrific to allow those who do not run a mainstream Operating System to enjoy this technology too.

**Comment by stratacast** [comment]
+1 here. It would be cool to see more support beyond the "trinity" of operating systems and see more support for open source operating systems.

**Comment by anoduck** [comment]
@stratacast Hopefully, once integrated into Emacs in the next release, it will be available. 

https://github.com/emacs-tree-sitter/elisp-tree-sitter/issues/243
