### ISSUE TITLE
Loading failing for `tree-sitter-langs`

### ISSUE THREAD

**Issue by meain** [emacs-tree-sitter/tree-sitter-langs#154]
Loading `tree-sitter-langs` fails as of now with an error like below, this is because the [release is having some issues](https://github.com/emacs-tree-sitter/tree-sitter-langs/actions/runs/3812974049). I am looking into what might be going on, but documenting it here in case someone else runs into this issue. You can switch to an older version to fix this, 388dcbbc237b2b1360e5b148e67b158eecede805 is a good commit.

```
tree-sitter-langs: Installing grammar bundle v0.12.10 (was v0.10.2)
Contacting host: github.com:443
Wrote /home/meain/dev/src/tree-sitter-langs/bin/tree-sitter-grammars.x86_64-unknown-linux-gnu.v0.12.10.tar.gz
[tree-sitter-langs] Running (tar -xvzf tree-sitter-grammars.x86_64-unknown-linux-gnu.v0.12.10.tar.gz) in /home/meain/dev/src/tree-sitter-langs/bin/
Configuring package avy...done
Configuring package scroll-on-drag...done

gzip: stdin: not in gzip format
/nix/store/l1qk6wapdkzj4q1dfiqv5vw479bsy0sw-gnutar-1.34/bin/tar: Child returned status 1
/nix/store/l1qk6wapdkzj4q1dfiqv5vw479bsy0sw-gnutar-1.34/bin/tar: Error is not recoverable: exiting now

Error running timer ‘require’: (error "Eager macro-expansion failure: (error \"Error calling (tar -xvzf tree-sitter-grammars.x86_64-unknown-linux-gnu.v0.12.10.tar.gz), exit code is 2\")")
```

**Comment by meain** [comment]
The release seems to be failing as the [signature](https://github.com/melpa/melpa/blob/275d4234e587f6e19d0c0701e02749886a31f4e9/package-build/package-build.el#L872) for `package-build--package` changed from what [cask is using as of now](https://github.com/cask/cask/blob/bc168a11d7881a62657cdf19bab2e7966033ec2c/cask.el#L1118)

**Comment by jcs090218** [comment]
There is a breaking changes, see https://github.com/melpa/package-build/issues/68

**Comment by jcs090218** [comment]
Allow me to bring up another alternative [Eask](https://github.com/emacs-eask/cli) (I'm the author of this tool), it's very similar to Cask but with better cross-platform capability.

Hope it's worth mentioning. 😅

**Comment by meain** [comment]
I have pushed a "fix" for this at https://github.com/ubolonton/cask/pull/3 . Eask look interesting, but I kinda don't wanna touch the CI if we can avoid it.

**Comment by victorolinasc** [comment]
Hi @ubolonton ! Could you push a patch version to Melpa stable or even any commit so that we have a new version on Melpa unstable? Still can´t enable this here as it breaks on the `tar` command as listed above. 

Thanks for your work on this!

**Comment by meain** [comment]
Hey @victorolinasc , sorry about it still being broken. The CI still fails on Perl grammar. Have to resolve this before we can make a release out.
https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/159

**Comment by victorolinasc** [comment]
ooops! Thanks @meain :)

**Comment by meain** [comment]
@victorolinasc A new release is now out and it should be back to working.
