### ISSUE TITLE
Including a fortran grammar

### ISSUE THREAD

**Issue by leclairm** [emacs-tree-sitter/tree-sitter-langs#158]
Hi emacs-tree-sitter devs,

First thanks a lot for your work. I'm very interested in having fortran included in the supported languages. There is an active repo where a fortran tree-sitter grammar is developed [1]. I tried to include it myself but unfortunately I don't appear to be skilled enough ... If you judge it feasible time/energy-wise, I'd be delighted to see it happen. Otherwise, still thanks for the great package!

[1] https://github.com/stadelmanma/tree-sitter-fortran

**Comment by jcs090218** [comment]
Added in #235.

**Comment by jcs090218** [comment]
Finally added in #238.
