### ISSUE TITLE
Installing built grammars

### ISSUE THREAD

**Issue by plasticmae** [emacs-tree-sitter/tree-sitter-langs#163]
Hi. I'm a little unclear on what to do with the grammars after they're built? Unless I'm reading them wrong the documentation doesn't say how to install them so that tree-sitter CLI and emacs understand it, just how to build them.

**Comment by meain** [comment]
You just have to require this package.  If you are using `use-package`, you should just be able to do

```emacs-lisp
(use-package tree-sitter-langs
  :ensure t
  :after tree-sitter)
```

**Comment by plasticmae** [comment]
Still getting the error
```
Warning (treesit): Cannot activate tree-sitter, because language grammar for bash is unavailable (not-found): (libtree-sitter-bash libtree-sitter-bash.so) No such file or directory
```
I am using emacs-29 branch though.

**Comment by meain** [comment]
We don't have compatibility with builtin treesit package which is what it looks like you are trying to use. This repo only works with https://github.com/emacs-tree-sitter/elisp-tree-sitter as of now. There is some discussion about supporting builtin treesit which you can follow at https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/157

**Comment by meain** [comment]
You can find more info about installing grammars for builtin tree-sitter at https://archive.casouri.cc/note/2023/tree-sitter-starter-guide/#Install%20language%20definitions . 

Here are a few other links to help you with built in tree-sitter:

- https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide?h=master#n34
- https://github.com/casouri/tree-sitter-module
- https://leba.dev/blog/2022/12/12/(ab)using-straightel-for-easy-tree-sitter-grammar-installations/

**Comment by plasticmae** [comment]
Ohhhh I see! I didn't realize they were separate packages. Thank you for clarifying.

**Comment by meain** [comment]
You can follow it at https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/144
