### ISSUE TITLE
No language registered for major mode ‘emacs-lisp-mode’

### ISSUE THREAD

**Issue by LazerJesus** [emacs-tree-sitter/tree-sitter-langs#179]
I am trying to get syntax highlighting for elisp but i am running into an issue. Namely running `tree-sitter-hl-mode` results in `tree-sitter--setup: No language registered for major mode ‘emacs-lisp-mode’`

And `tree-sitter-major-mode-language-alist` does indeed not contain lisp nor elisp.

This is the total extend of my tree-sitter setup. 

```
(straight-use-package tree-sitter)
(straight-use-package tree-sitter-langs)

(require 'tree-sitter)
(require 'tree-sitter-langs)

(global-tree-sitter-mode)
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)
```
what am i doing wrong?

**Comment by meain** [comment]
You are not doing anything wrong, it is just that we don't have tree-sitter grammar for emacs lisp yet.

**Comment by meain** [comment]
> EmacsConf ‘22 had a treesitter demo that featured syntax highlighting, structural editing and all kinds of goodiegoodies.

That was my talk ;)

> Is that in the works somewhere?

I don't know of any tree-sitter implementations specifically for Emacs lisp. With that said, if you are looking for structural editing in lisp, there is already things like [paredit](http://paredit.org/).

FYI, you can see the languages we support [here](https://github.com/emacs-tree-sitter/tree-sitter-langs/tree/master/repos).

**Comment by FinnFrotscher** [comment]
such a good talk! it strongly motivated me to try out treesitter. the concept of structural editing is super appealing. i want to get into it haha

i started work on an elisp grammar, but its above my paygrade. anyone interested could use this as a jumping-off point. a lot of it was generated in colab with copilot.
https://github.com/FinnFrotscher/elisp-treesitter-grammar

**Comment by tralph3** [comment]
There's [this](https://github.com/Wilfred/tree-sitter-elisp). I didn't test it myself tho.

**Comment by jcs090218** [comment]
Added in #215.
