### ISSUE TITLE
shipping queries with themes

### ISSUE THREAD

**Issue by p00f** [emacs-tree-sitter/tree-sitter-langs#182]
what is the correct way to ship queries with a theme?

(sorry if this is not the right repo, just figured i'll ask here since the queries are here)

**Comment by jcs090218** [comment]
No, queries defined faces and faces should be used to configure by theme.

Hope the information helps! :)

**Comment by p00f** [comment]
No, I don't like the default queries, they don't match my theme's philosophy

**Comment by jcs090218** [comment]
Do you mean the color? Queries only control the region so you would have to configure colors yourself.

**Comment by p00f** [comment]
No, I need to control the region - believe me, I know what I'm talking about  😉, I have worked with treesitter before 
https://github.com/p00f/nvim-ts-rainbow/
https://github.com/p00f/alabaster.nvim

Please stop treating me otherwise

**Comment by jcs090218** [comment]
> No, I need to control the region - believe me

If you are talking about the region, then yes, you can open PRs for this.

> I know what I'm talking about 😉, I have worked with treesitter before

I didn't say you never worked with tree-sitter before. Not sure where you got the result from. 🤔 But okay. Have a nice day. :)

**Comment by p00f** [comment]
I just realised treesit.el has the captures I want, thanks for your time
