### ISSUE TITLE
Add ocaml grammar for interfaces

### ISSUE THREAD

**Issue by nojb** [emacs-tree-sitter/tree-sitter-langs#189]
Hello, thank you for your useful project. The https://github.com/tree-sitter/tree-sitter-ocaml project actually defines two grammars, one for implementations (which is already included in `tree-sitter-langs`) and one for interfaces, which is missing. The missing one is in the `interface` subdirectory: https://github.com/tree-sitter/tree-sitter-ocaml/tree/master/interface.

Would it be possible to add it? Thanks!

**Comment by jcs090218** [comment]
I've added in #251.
