### ISSUE TITLE
BUG: some tree-sitter repos are quite old, like r

### ISSUE THREAD

**Issue by beyondpie** [emacs-tree-sitter/tree-sitter-langs#195]
Hi there,

When I use tree-sitter-r, I notice that the version is pointed to a very old one (2022), while the source of the[ tree-sitter-r ](https://github.com/r-lib/tree-sitter-r) has been updated recently. 
I think the potential bug is because the use of "master" instead of "main" branch
https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/944a734b7c3a5922a7e9a2009a9165e2dc195b18/.gitmodules#L229

In the meanwhile, if I compile the corresponding tree-sitter myself, where can I find the generated file? I plan to put it into my emacs tree-sitter directory, but cannot find it after using `script/compile r`

Thanks!
Songpeng

**Comment by jcs090218** [comment]
cc @meain 

> In the meanwhile, if I compile the corresponding tree-sitter myself, where can I find the generated file? I plan to put it into my emacs tree-sitter directory, but cannot find it after using `script/compile r`

It should be generated in your current working directory. 🤔

**Comment by beyondpie** [comment]
@jcs090218 
Thanks for the reply!  Following the README, after installing the depencies like Tree-sitter-cli, I can now have the binary files under bin/. 

But even I change it to main, I cannot update the tree-sitter-r.....

**Comment by jcs090218** [comment]
> But even I change the branch from master to main for submodule r, I cannot have the latest tree-sitter-r.

**Comment by meain** [comment]
FYI, `elisp-tree-sitter` requires an older version of `tree-sitter` to work well. (ref: https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/186).

Also, you can use [`script/compile r`](https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/master/script/compile) once you have pulled the latest version of `r` to compile the grammar.

**Comment by beyondpie** [comment]
@jcs090218 @meain 
Thanks for your replies!  when i use the old version of tree-sitter, I can now have the lasted tree-sitter-r.
Songpeng

**Comment by neuromagus** [comment]
My 50 cents. Something wrong with HTML.dll. Emacs did not see only this file (html-ts-mode) on Windows. If u have a time (i did not have VS or something else for compiling), please, update this grammar. 

Thanks a lot for this repo (modest Windows user).

**Comment by jcs090218** [comment]
I've added the submodule update workflow. Now most grammars are up to date.
