### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by loafofpiecrust** [emacs-tree-sitter/tree-sitter-langs#20]
I'm really excited about this package. `font-lock` is the main slow-down when I just type in an `org` or `markdown` buffer, so faster highlighting would be amazing. I've seen [`tree-sitter-markdown`](https://github.com/ikatyang/tree-sitter-markdown) and I might try to use that project as a base for `tree-sitter-org` if nobody has done that before!

**Comment by tani** [comment]
Please consider https://www.reddit.com/r/neovim/comments/rg97j4/treesitter_for_markdown/

**Comment by jcs090218** [comment]
It's added in #146. :)
