### ISSUE TITLE
Add dart grammar to tree sitter

### ISSUE THREAD

**Issue by ram535** [emacs-tree-sitter/tree-sitter-langs#22]
This is just a request for adding dart grammar to tree sitter.
Thanks.

**Comment by shackra** [comment]
> Creating new grammars is out of emacs-tree-sitter's scope.
> 
> There doesn't seem to be an existing tree-sitter grammar for Dart.
> If you know one, please reopen the issue. I would check it out.

sorry for hijacking the thread but I need to ask: if I create a new major mode to Emacs, I should provide the grammars along with my package and make emacs-tree-sitter a dependency or how should a major-mode author go about this?

**Comment by jsmestad** [comment]
@shackra did you find an answer to this?

**Comment by shackra** [comment]
> @shackra did you find an answer to this?

nope

**Comment by jcs090218** [comment]
Added in #199.
