### ISSUE TITLE
Add mermaid grammar

### ISSUE THREAD

**Issue by slackline** [emacs-tree-sitter/tree-sitter-langs#248]
There is a new Emacs major [mermaid-ts-mode](https://github.com/JonathanHope/mermaid-ts-mode), it would be great if the required grammar [tree-sitter-mermaid](https://github.com/monaqa/tree-sitter-mermaid) could be included in this package.

**Comment by jcs090218** [comment]
Added in #249.

**Comment by slackline** [comment]
Super quick, thank you :pray:
