### ISSUE TITLE
Error with java-ts-mode and Emacs 29.1.2 on Windows 64 bits.

### ISSUE THREAD

**Issue by PascalQuesseveur** [emacs-tree-sitter/tree-sitter-langs#275]
I run emacs -Q, then:

(setq major-mode-remap-alist
 '((java-mode . java-ts-mode)))

I get the following error when loading a java source file:

Error during redisplay: (jit-lock-function 1) signaled
(treesit-query-error "Node type error at" 382 "(annotation_type_declaration
 name: (identifier) @font-lock-type-face) (interface_declaration
 name: (identifier) @font-lock-type-face) (class_declaration
 name: (identifier) @font-lock-type-face) (record_declaration
 name: (identifier) @font-lock-type-face) (enum_declaration
 name: (identifier)
 @font-lock-type-face) (constructor_declaration
 name: (identifier)
 @font-lock-type-face) (compact_constructor_declaration
 name: (identifier) @font-lock-type-face) (field_access
 object: (identifier)
 @font-lock-type-face) (method_reference (identifier)
 @font-lock-type-face) (scoped_identifier (identifier)
 @font-lock-constant-face) ((scoped_identifier name: (identifier)
 @font-lock-type-face) (#match \"\\\\`[A-Z]\"
 @font-lock-type-face)) (type_identifier) @font-lock-type-face
 [(boolean_type) (integral_type) (floating_point_type) (void_type)]
 @font-lock-type-face" "Debug the query with `treesit-query-validate'")

**Comment by jcs090218** [comment]
You are using the built-in treesit.el, and not this package. You should report this bug to the Emacs devel and not here!

**Comment by Eli-Zaretskii** [comment]
Do the language grammar libraries on this site require a version of treesit.el that is different from the built-in one?  If so, where can one see the treesit.el that is compatible with the grammar libraries on this site?

**Comment by dgutov** [comment]
Or if you permit me asking: which repository revision the java tsx grammar was built from?

**Comment by jcs090218** [comment]
> Do the language grammar libraries on this site require a version of treesit.el that is different from the built-in one? If so, where can one see the treesit.el that is compatible with the grammar libraries on this site?

No, it uses the [elisp-tree-sitter](https://github.com/emacs-tree-sitter/elisp-tree-sitter), which uses the Rust bindings.

**Comment by Eli-Zaretskii** [comment]
And the language grammar, as your build it here, knows that Rust bindings will be used?
IOW, what is the technical reason why your grammar libraries are not suitable for the built-in treesit.el and the major modes which use treesit.el?
