### ISSUE TITLE
Upgrade the julia repo?

### ISSUE THREAD

**Issue by linwaytin** [emacs-tree-sitter/tree-sitter-langs#288]
Is it possible to upgrade the `tree-sitter-julia` to the newest version? It seems the version in this package is from more than 2 year ago. 

I asked this because I ran into some bug in parsing some julia code. The new version should fix the issue.

**Comment by jcs090218** [comment]
See #289.

**Comment by linwaytin** [comment]
Thanks for taking care of this issue. 

On my laptop I can use Emacs 29 and the built-in `treesit` package, which can compile the newest version of the julia grammar from the repo. With that, I am almost certain that the bug has been fixed in the new version, so it would be nice if we can update this pacakge to use the newest version.

**Comment by jcs090218** [comment]
Duplicate of #117
