### ISSUE TITLE
D Support

### ISSUE THREAD

**Issue by nordlow** [emacs-tree-sitter/tree-sitter-langs#38]
Would it be possible to add support for the D programming language via

https://github.com/CyberShadow/tree-sitter-d

?

Ping, @CyberShadow.

**Comment by CyberShadow** [comment]
CyberShadow/tree-sitter-d is not yet ready to be used in this way. It still [fails to parse a lot of valid D code](https://github.com/CyberShadow/tree-sitter-d/issues/3), and it does not yet have any syntax highlighting rules.

**Comment by nordlow** [comment]
I see. Closing this then. Thanks for now.
