### ISSUE TITLE
Rust grammar very out of date

### ISSUE THREAD

**Issue by snyball** [emacs-tree-sitter/tree-sitter-langs#381]
Hi, I see the Rust grammar hasn't been updated for about 3 years, are there any blockers for this?

There's parsing issues with with e.g the `let Some(x) = y else { return }` pattern, which was added sometime in the last 3 years.

**Comment by jcs090218** [comment]
I'm working on the automation for updating parsers. For rust, see #358.

**Comment by jcs090218** [comment]
FYI, it will take a while for me to merge this since I've only recently started doing the automation. 😅 But I promise we will have more parsers keep up to date.

**Comment by snyball** [comment]
> FYI, it will take a while for me to merge this since I've only recently started doing the automation. 😅 But I promise we will have more parsers keep up to date.

Don't worry about it! :) Is there an easy way for me to use the new grammar locally in the meantime?

**Comment by jcs090218** [comment]
You can try compile it yourself. See https://github.com/emacs-tree-sitter/tree-sitter-langs?tab=readme-ov-file#building-grammars-from-source.

**Comment by npajkovsky** [comment]
I would like to have this one updated too.

**Comment by jcs090218** [comment]
There are some errors while updating the rust parser. I'm working on it!

**Comment by jcs090218** [comment]
Done!
