### ISSUE TITLE
Maybe the Markdown parser should be updated 

### ISSUE THREAD

**Issue by maikol-solis** [emacs-tree-sitter/tree-sitter-langs#502]
In the repos folder, I see this parser for markdown that hasn't been updated in 3 years. 

https://github.com/ikatyang/tree-sitter-markdown/tree/8b8b77af0493e26d378135a3e7f5ae25b555b375

However, this is a new parser that is updated regularly, and it could be used for the project.   

https://github.com/tree-sitter-grammars/tree-sitter-markdown

WDYT?

**Comment by jcs090218** [comment]
Sounds good to me! Sorry, I am a little busy, so I will do this when I have time. But PRs are always welcome! :)

**Comment by maikol-solis** [comment]
Perfect. I just created a PR with the fix. 
Best.
