### ISSUE TITLE
bump tree sitter java

### ISSUE THREAD

**Issue by jeetelongname** [emacs-tree-sitter/tree-sitter-langs#52]
Hi!

Recently a bug was found in the [java queries for evil textobj tree-sitter](https://github.com/meain/evil-textobj-tree-sitter/issues/30) this was found out to be a discrepancy with the grammer and the queries where we are using the older node name while the queries are using an updated version. bumping the grammar  will fix this.

**Comment by jeetelongname** [comment]
any word on this?

**Comment by ubolonton** [comment]
Yeah, please create a pull request for it.

**Comment by jeetelongname** [comment]
ah awesome ill get on that, thanks!
