### ISSUE TITLE
Cannot find DLL:  (libtree-sitter-python libtree-sitter-python.dll) No such file or directory

### ISSUE THREAD

**Issue by vjohansen** [emacs-tree-sitter/tree-sitter-langs#545]
_GNU Emacs 29.2 (build 2, x86_64-w64-mingw32) of 2024-02-01_

When I call python-ts-mode in a py-file it fails with 

    ■  Warning (treesit): Cannot activate tree-sitter, because language grammar for python is unavailable (not-found): (libtree-sitter-python libtree-sitter-python.dll) No such file or directory

Steps

- Install tree-sitter-langs-0.12.175 via Emacs package manger (ths gives me ~\emacs-29\.emacs.d\elpa\tree-sitter-langs-0.12.175\bin\python.dll )
- restart emacs via **runemacs -q**
- open py file
- call python-ts-mode

Result: it looks for libtree-sitter-python.dll

python-ts-mode calls (treesit-ready-p 'python) which throws an error because (treesit-language-available-p lang t) fails

treesit-language-available-p is a C function

**Comment by jcs090218** [comment]
This is `tree-sitter.el` and not the built-in `treesit.el`. 🤔 I think you are looking for https://github.com/renzmann/treesit-auto.

**Comment by vjohansen** [comment]
Seems related to #144 and #157 

The latter includes a pull request that seems to copy the dlls

There is also some potential info in #163

It would be nice if your main READ/frontpage include info about not to use this with Emacs 29 or whatever the case may be. After reading in #163 the confusion just increases

**Comment by vjohansen** [comment]
Thanks. I tried it but could not get it working. Will try again.

Maybe add some info on your frontpage/READ about this

I am trying to upgrade to Emacs 29 (windows) and find it difficult to understand treesit support

**Comment by vjohansen** [comment]
treesit-auto tries to *compile* with cc on windows so that does not work and a substitute for a package precompiled DLLs
  

      Warning (treesit): Error encountered when installing language grammar: (file-missing Searching for program No such file or directory cc)

**Comment by jcs090218** [comment]
`tree-sitter.el` is not the same as `treesit.el`. You should open a bug report on their repo!

> Maybe add some info on your frontpage/READ about this

I agree. This can be quite confusing for people who are new to Emacs.
