### ISSUE TITLE
No language registered for major mode ‘LaTeX-mode’

### ISSUE THREAD

**Issue by Nidish96** [emacs-tree-sitter/tree-sitter-langs#565]
I didn't notice from which version, but I'm now getting an error "No language registered for major mode ‘LaTeX-mode’" whenever I try to enable tree-sitter-mode on a latex buffer.

It was working fine previously.

**Comment by jcs090218** [comment]
The latex major has been rename to something else. That's probably why. 🤔

**Comment by jcs090218** [comment]
Fixed in f689c3d6bd55935b2cfd450e55acaf7d9c94dacd.
