### ISSUE TITLE
No faces ae applied to c++ macro definition.

### ISSUE THREAD

**Issue by amosbird** [emacs-tree-sitter/tree-sitter-langs#63]
How to reproduce:

1. Open vanillar emacs and load both tree-sitter and tree-sitter-langs.
2. Open https://raw.githubusercontent.com/ClickHouse/ClickHouse/master/src/Core/Settings.h
3. enable tree-sitter-mode and tree-sitter-hl-mode

Expect:

Fields and Strings should be highlighted inside macro definition.

Actual:

No faces are applied to macro definition.

![image](https://user-images.githubusercontent.com/5085485/147907849-bc39441d-3cae-4f78-9e19-6b58760bf04e.png)

**Comment by ubolonton** [comment]
This is because the C grammar doesn't parse the content of macro definitions. The other way for this to work is for [elisp-tree-sitter to support multiple sub-trees](https://github.com/emacs-tree-sitter/elisp-tree-sitter/issues/33).

**Comment by amosbird** [comment]
> This is because the C grammar doesn't parse the content of macro definitions

Do you mean that tree-sitter doesn't understand what `M` is?

**Comment by ubolonton** [comment]
It means the whole red box is parsed as a `preproc_arg`.

**Comment by amosbird** [comment]
> It means the whole red box is parsed as a `preproc_arg`.

Yeah, I mean is it because that tree-sitter doesn't understand what `M` is, and has to parse the definition as a whole?

**Comment by ubolonton** [comment]
Please see tree-sitter's [C grammar](https://github.com/tree-sitter/tree-sitter-c/blob/f71e80b/grammar.js#L94).
