### ISSUE TITLE
Update Swift language. Current is not the most active one.

### ISSUE THREAD

**Issue by konrad1977** [emacs-tree-sitter/tree-sitter-langs#72]
Looks like this repo is the one that is undergoing active development, maybe switch to this one?

https://github.com/alex-pinkus/tree-sitter-swift

**Comment by ubolonton** [comment]
Yeah. Can you [try it out](https://github.com/emacs-tree-sitter/tree-sitter-langs#adding-a-new-grammar) and open a pull request?

**Comment by konrad1977** [comment]
Yeah that worked. Used the highlight.scm also. Now I can adjust highlightning. I am no ninja at git so I actually did a copy of the repo on disk and then run script/compile swift.

https://github.com/alex-pinkus/tree-sitter-swift this seems to be alot more mature than the previous one. Maybe update?

**Comment by alex-pinkus** [comment]
FYI, grammar load time (especially for swift) is greatly improved if the grammar is generated using `tree-sitter` version `0.20.4` with the command `tree-sitter generate --abi 14`. See https://github.com/tree-sitter/tree-sitter/pull/1589.

**Comment by konrad1977** [comment]
Hi @alex-pinkus I think we cannot use anything above 19.5 for now, for comparbility reasons.

**Comment by konrad1977** [comment]
I noticed that most of them can change :background but not :foreground. Any ideas why @ubolonton ? (in emacs when I setup my own theme.

**Comment by ubolonton** [comment]
> I noticed that most of them can change :background but not :foreground.

This sounds like an issue with your (theme) setup. In any case, you would have better luck with one of these:
- https://emacs.stackexchange.com/
- https://www.reddit.com/r/emacs/
- https://discord.com/invite/qvGgnVx (They have rooms for general Emacs questions, not just Doom-specific.)

**Comment by woolsweater** [comment]
I also have a Swift grammar that I have been developing and using with emacs-tree-sitter for the past year: https://gitlab.com/woolsweater/tree-sitter-swifter . I was unaware of this other effort until now; I came here to mention mine and saw this issue instead. 😅

**Comment by konrad1977** [comment]
@woolsweater How do I try out your grammar? How much difference does it do, I never got it work with Emacs and Swift and I am curious if it's worth the effort.

**Comment by woolsweater** [comment]
@konrad1977 I believe the best way to try any alternative grammar is to follow the tree-sitter-langs instructions for [Building Grammars From Source](https://github.com/emacs-tree-sitter/tree-sitter-langs#building-grammars-from-source). You would just change the appropriate language submodule to point to the alternative repo.

From there how you load it into Emacs depends on your choice of package manager. If you happen to use straight.el, I can point you [to how I do it in my .emacs.d](https://gitlab.com/woolsweater/dotemacs.d/-/blob/b263b4dbbe097c2749d2eb022528de2be406da27/startup/externals.el#L601-609). I'm afraid I am not familiar enough with other managers to offer advice there.

**Comment by konrad1977** [comment]
@woolsweater do you notice any slow downs? Could you share a screen shot with and without tree-sitter enabled? (Is it worth it)?

**Comment by woolsweater** [comment]
@konrad1977 Good idea! I have added a README and some screenshots to my repo. I find the performance of elisp-tree-si/tter and my grammar to be a non-issue in daily use. It was already fine in Emacs 27 and pretty much _everything_ seems snappier with 28 🙂 It is definitely worth it, not just for Swift but for any supported language.

**Comment by woolsweater** [comment]
@ubolonton elisp-tree-sitter does not support multiple grammars for a programming language, does it? I am unsure how best to handle this situation where there are two options. (I doubt that our grammars are mergeable.)

**Comment by konrad1977** [comment]
@woolsweater I compiled it my self and got it working yesterday. Works great (for the most). Didn't notice any speed bumps but I'm currently on a M1 Max MBP.

**Comment by konrad1977** [comment]
@ubolonton maybe its a good idea to change the languag to @woolsweater version? The old one havent been updated in 3 years (and doesn't include any rules so its more or less useless). I havent tried @alex-pinkus version but it would be nice to try that one to. @woolsweater maybe you have compared your version with @alex-pinkus?
