### ISSUE TITLE
Request to bump R grammar

### ISSUE THREAD

**Issue by KaiAragaki** [emacs-tree-sitter/tree-sitter-langs#735]
R recently got a fairly major overhaul to its grammar. I don't see any blockers in the PR (https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/640) - is it possible to bump R's grammar for the next release? Thank you for your time!

**Comment by jcs090218** [comment]
The CI didn't pass the last time. Let me re-run it! 🤔

**Comment by KaiAragaki** [comment]
Ah, thanks for pointing it out. That must be the issue! Is this something that should be brought to the attention of upstream maintainers?

**Comment by jcs090218** [comment]
By looking at the error, we need to update the queries since the old one isn't compatible with the latest grammar. 🤔
