### ISSUE TITLE
Issues compiling locally on MacOS

### ISSUE THREAD

**Issue by ethan-leba** [emacs-tree-sitter/tree-sitter-langs#78]
I&rsquo;ve been looking into the TS langs codebase to see how we can allow for
local compilation of abritrary repos (as opposed to limiting ourselves
to the submodules). However, I appear to be unable to compile languages
locally via `script/compile`, it seems to run generate/test and then
exit without emitting any dylibs:

    ~/D/OSS/tree-sitter-langs [master] λ script/compile python
      [tree-sitter-langs] Processing python
      [tree-sitter-langs] Running (tree-sitter generate) in *Users/ethanleba/Documents/OSS/tree-sitter-langs/repos/python*
      [tree-sitter-langs] Running (tree-sitter test) in *Users/ethanleba/Documents/OSS/tree-sitter-langs/repos/python*
      &#x2026;
    
      ~/D/OSS/tree-sitter-langs [master] λ

Is MacOS simply unsupported right now, or is something going wrong here?

**Comment by ubolonton** [comment]
Maybe you have a new version of the `tree-sitter` CLI? The output location of dylibs was changed and could no longer be customized. I opened an issue for that: https://github.com/tree-sitter/tree-sitter/issues/1336.

**Comment by ethan-leba** [comment]
Ah, looks like that did the trick. I was a bit thrown off by there being no evident compilation step -- if I understand correctly, we're piggybacking off of `tree-sitter test` generating the dylib before testing?

**Comment by ubolonton** [comment]
> if I understand correctly, we're piggybacking off of `tree-sitter test` generating the dylib before testing?

Yeah, most of the time.

**Comment by ethan-leba** [comment]
Makes sense, thanks!
