### ISSUE TITLE
Instructions for adding a new mode

### ISSUE THREAD

**Issue by knobo** [emacs-tree-sitter/tree-sitter-langs#82]
I would like to add support for kotlin. I have now been able to load the kotlin.so file and now I must create a 
"highlights.scm" file. What would be a good procedure for creating a file like that? Should I just examine the kotlin/grammar.js file, or is there a more automated way of doing that?

**Comment by knobo** [comment]
When I enable tree-sitter-indent-mode I see there is some variable that needs to be set.
For example: `kotlin-indent-offset` and `tree-sitter-indent-kotlin-scopes`
kotlin-indent-offset was easy, but how should tree-sitter-indent-kotlin-scopes look like?
And are there any other variables that needs to be set?

**Comment by knobo** [comment]
How can I reload the highlights.scm file after making a change?

**Comment by ubolonton** [comment]
> What would be a good procedure for creating a file like that? 
> Should I just examine the kotlin/grammar.js file, or is there a more automated way of doing that?

There is no automated way to do that. Code highlighting is subjective, and not all languages are the same. You should:
- Look at `grammar.js` to know what node types are available, and how they are structured.
- Be familiar with the [query language](https://emacs-tree-sitter.github.io/syntax-highlighting/queries/).
- Follow tree-sitter-langs's [conventions](https://emacs-tree-sitter.github.io/syntax-highlighting/#tree-sitter-langs). (You may want to consult highlighting patterns that this package provides for Rust, Python, JavaScript, TypeScript.)
